title: Minimal theme
logo: /assets/img/kiwi-thompson-r0wgHisWr4o-unsplash.jpg
description: Image by Kiwi Thompson, Found on Unsplash
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
